version: 1

disable_existing_loggers: True

formatters:

  brief:
    format: "%(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"

  precise:
    format: "%(asctime)s - %(name)s - %(levelname)-9s - %(filename)-8s : %(lineno)s line - %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: brief
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: brief
    filename: log
    maxBytes: 1024000
    backupCount: 10

loggers:
  logger:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no

root:
  level: WARNING
  handlers: [ console, file ]
  propagate: no

